#!/usr/bin/env bash
# Netrunner classroom deployment launcher

set -euo pipefail
cd "$(dirname "$(readlink -f "$0" 2>/dev/null || echo "$0")")"

random_hex() {
    local bytes="$1"
    if command -v openssl >/dev/null 2>&1; then
        openssl rand -hex "$bytes"
    else
        od -An -N "$bytes" -tx1 /dev/urandom | tr -d ' \n'
    fi
}

generate_env() {
    local deployment_mode="${1:-student}"
    if [[ -f .env ]]; then
        chmod 600 .env
        return
    fi

    umask 077
    if [[ -f data/postgres/PG_VERSION || -d data/influxdb2/engine ]]; then
        echo "❌ Eksisterende driftsdata blev fundet, men den tilhørende .env mangler."
        echo "   Gendan den matchende .env fra backup; Netrunner genbruger ikke"
        echo "   kendte standardkoder eller genererer secrets, som låser gamle data."
        exit 1
    fi

    local db_password influx_password influx_token
    db_password="$(random_hex 24)"
    influx_password="$(random_hex 24)"
    influx_token="$(random_hex 32)"

    {
        echo "# Generated by ./start.sh. Keep this file private."
        echo "NETRUNNER_DEPLOYMENT_MODE=${deployment_mode}"
        if [[ "$deployment_mode" == "server" ]]; then
            echo "NETRUNNER_ADMIN_PASSWORD=$(random_hex 18)"
            echo "NETRUNNER_ANALYST_PASSWORD=$(random_hex 18)"
        fi
        echo "NETRUNNER_STUDENT_PASSWORD=$(random_hex 12)"
        echo "NETRUNNER_SECRET_KEY=$(random_hex 48)"
        echo "NETRUNNER_AGENT_TOKEN=$(random_hex 32)"
        echo "NETRUNNER_INTERNAL_TOKEN=$(random_hex 32)"
        echo "NETRUNNER_DB_PASSWORD=${db_password}"
        echo "INFLUXDB_ADMIN_USERNAME=netrunner-admin"
        echo "INFLUXDB_ADMIN_PASSWORD=${influx_password}"
        echo "INFLUXDB_TOKEN=${influx_token}"
        echo "INFLUXDB_ORG=netrunner"
        echo "INFLUXDB_BUCKET=traffic"
        echo "NETRUNNER_CORS_ORIGINS=http://localhost:8000,http://127.0.0.1:8000"
        echo "GNS3_PROJECTS_PATH=./data/gns3_projects"
        echo "OPENAI_API_KEY="
        echo "NETRUNNER_ENABLE_AI_TRIAGE=0"
    } > .env
    chmod 600 .env
    echo "✅ Oprettede .env til ${deployment_mode}-tilstand med stærke lokale adgangsoplysninger."
}

show_credentials() {
    if [[ ! -f .env ]]; then
        echo "Ingen .env fundet. Kør ./start.sh init først."
        exit 1
    fi
    echo "Netrunner student-login:"
    awk -F= '
        $1 == "NETRUNNER_STUDENT_PASSWORD" {print "  student: " $2}
    ' .env
}

sync_postgres_password() {
    echo "🔐 Synkroniserer PostgreSQL-adgang uden at ændre data..."
    "${COMPOSE[@]}" up -d postgres

    local db_ready=0
    for _ in $(seq 1 30); do
        if "${COMPOSE[@]}" exec -T postgres \
            pg_isready -U netrunner -d netrunner >/dev/null 2>&1; then
            db_ready=1
            break
        fi
        sleep 2
    done

    if [[ "$db_ready" -ne 1 ]]; then
        echo "❌ PostgreSQL blev ikke klar til adgangskodemigrering."
        "${COMPOSE[@]}" logs --tail=80 postgres
        return 1
    fi

    # POSTGRES_PASSWORD only initializes a new volume. Synchronize the role on
    # every release start so an existing classroom database follows .env too.
    "${COMPOSE[@]}" exec -T postgres sh -ceu \
        'printf "%s\n" "ALTER ROLE netrunner PASSWORD :'\''db_password'\'';" | psql --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" --set=ON_ERROR_STOP=1 --set="db_password=$POSTGRES_PASSWORD"' \
        >/dev/null
}

case "${1:-start}" in
    credentials)
        show_credentials
        exit 0
        ;;
    init)
        deployment_mode="${2:-student}"
        if [[ "$deployment_mode" != "student" && "$deployment_mode" != "server" ]]; then
            echo "Tilstand skal være 'student' eller 'server'."
            exit 2
        fi
        mkdir -p data/postgres data/influxdb2 data/ssh data/gns3_config \
            data/gns3_projects data/wireguard
        chmod 700 data/ssh
        generate_env "$deployment_mode"
        echo "Kør ./start.sh for at bygge og starte Netrunner."
        exit 0
        ;;
    start)
        ;;
    *)
        echo "Brug: ./start.sh [start|credentials]"
        echo "      ./start.sh init [student|server]"
        exit 2
        ;;
esac

echo "================================================================"
echo "                   NETRUNNER CYBERDECK OS                       "
echo "================================================================"

if [[ "$(uname -s)" != "Linux" ]]; then
    echo "❌ Denne release er valideret til en Linux Docker-vært."
    echo "   Hardware-, host-network- og GNS3-funktioner understøttes ikke"
    echo "   som en fuld classroom deployment på macOS/Windows."
    exit 1
fi

if ! command -v docker >/dev/null 2>&1; then
    echo "❌ Docker er ikke installeret."
    exit 1
fi

if ! docker info >/dev/null 2>&1; then
    echo "❌ Docker-daemonen kører ikke, eller brugeren mangler adgang."
    exit 1
fi

if docker compose version >/dev/null 2>&1; then
    COMPOSE=(docker compose)
elif command -v docker-compose >/dev/null 2>&1; then
    COMPOSE=(docker-compose)
else
    echo "❌ Docker Compose v2 blev ikke fundet."
    exit 1
fi

mkdir -p data/postgres data/influxdb2 data/ssh data/gns3_config \
    data/gns3_projects data/wireguard
chmod 700 data/ssh
# A fresh clone is safe for student distribution by default. Instructors who
# host a shared classroom server initialize it explicitly with `init server`.
generate_env "student"

echo "🔎 Validerer deployment-konfiguration..."
"${COMPOSE[@]}" config --quiet

echo "🚀 Bygger og starter Netrunner..."
if ! "${COMPOSE[@]}" build; then
    echo "❌ Docker-build fejlede. Den tidligere kørende release er ikke erstattet."
    exit 1
fi
sync_postgres_password
if ! "${COMPOSE[@]}" up -d; then
    echo "❌ Containeropstart fejlede. Seneste applikationslogs:"
    "${COMPOSE[@]}" logs --tail=80 netrunner terminal-mux
    exit 1
fi

echo "⏳ Venter på at backend og database bliver klar..."
ready=0
for _ in $(seq 1 90); do
    if curl -fsS http://127.0.0.1:8000/api/ready >/dev/null 2>&1; then
        ready=1
        break
    fi
    sleep 2
done

if [[ "$ready" -ne 1 ]]; then
    echo "❌ Netrunner blev ikke ready inden for tre minutter."
    "${COMPOSE[@]}" ps
    "${COMPOSE[@]}" logs --tail=160 netrunner
    exit 1
fi

echo ""
echo "================================================================"
echo "                 NETRUNNER ER KLAR                              "
echo "================================================================"
echo "🌐 Lokal URL: http://localhost:8000"
echo "🔐 Vis loginoplysninger: ./start.sh credentials"
echo "📋 Status: docker compose ps"
echo "🧾 Logs:   docker compose logs -f netrunner"
echo "================================================================"
