// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type DpiRule struct {
	_         structs.HostLayout
	RuleId    uint32
	Dport     uint16
	SigLen    uint16
	Signature [8]uint8
}

// LoadDpi returns the embedded CollectionSpec for Dpi.
func LoadDpi() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_DpiBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Dpi: %w", err)
	}

	return spec, err
}

// LoadDpiObjects loads Dpi and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*DpiObjects
//	*DpiPrograms
//	*DpiMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadDpiObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadDpi()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// DpiSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type DpiSpecs struct {
	DpiProgramSpecs
	DpiMapSpecs
	DpiVariableSpecs
}

// DpiProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type DpiProgramSpecs struct {
	SocketDpi *ebpf.ProgramSpec `ebpf:"socket_dpi"`
}

// DpiMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type DpiMapSpecs struct {
	Events   *ebpf.MapSpec `ebpf:"events"`
	RulesMap *ebpf.MapSpec `ebpf:"rules_map"`
}

// DpiVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type DpiVariableSpecs struct {
	UnusedEvent *ebpf.VariableSpec `ebpf:"unused_event"`
	UnusedRule  *ebpf.VariableSpec `ebpf:"unused_rule"`
}

// DpiObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadDpiObjects or ebpf.CollectionSpec.LoadAndAssign.
type DpiObjects struct {
	DpiPrograms
	DpiMaps
	DpiVariables
}

func (o *DpiObjects) Close() error {
	return _DpiClose(
		&o.DpiPrograms,
		&o.DpiMaps,
	)
}

// DpiMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadDpiObjects or ebpf.CollectionSpec.LoadAndAssign.
type DpiMaps struct {
	Events   *ebpf.Map `ebpf:"events"`
	RulesMap *ebpf.Map `ebpf:"rules_map"`
}

func (m *DpiMaps) Close() error {
	return _DpiClose(
		m.Events,
		m.RulesMap,
	)
}

// DpiVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadDpiObjects or ebpf.CollectionSpec.LoadAndAssign.
type DpiVariables struct {
	UnusedEvent *ebpf.Variable `ebpf:"unused_event"`
	UnusedRule  *ebpf.Variable `ebpf:"unused_rule"`
}

// DpiPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadDpiObjects or ebpf.CollectionSpec.LoadAndAssign.
type DpiPrograms struct {
	SocketDpi *ebpf.Program `ebpf:"socket_dpi"`
}

func (p *DpiPrograms) Close() error {
	return _DpiClose(
		p.SocketDpi,
	)
}

func _DpiClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed dpi_bpfel.o
var _DpiBytes []byte
