"""threat_intel_schema

Revision ID: 07f3a9bbcb3a
Revises:
Create Date: 2026-06-17 19:04:13.354620

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "07f3a9bbcb3a"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("user_id", sa.String(length=100), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("resource", sa.String(length=100), nullable=False),
        sa.Column("details", sa.Text(), nullable=False),
        sa.Column("timestamp", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "beacon_nodes",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("ip", sa.String(length=100), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("password", sa.String(length=255), nullable=False),
        sa.Column("encrypted", sa.Boolean(), nullable=False),
        sa.Column("target_server_ip", sa.String(length=100), nullable=False),
        sa.Column("csi_mode", sa.String(length=50), nullable=False),
        sa.Column("sample_rate", sa.Integer(), nullable=False),
        sa.Column("udp_port", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "firmwares",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("version", sa.String(length=50), nullable=False),
        sa.Column("arch", sa.String(length=20), nullable=False),
        sa.Column("url", sa.String(length=255), nullable=False),
        sa.Column("uploaded_at", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "integrations",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("url", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "nodes",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("host", sa.String(length=100), nullable=False),
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=True),
        sa.Column("transport", sa.String(length=20), nullable=False),
        sa.Column("device_type", sa.String(length=50), nullable=False),
        sa.Column("created", sa.String(length=50), nullable=True),
        sa.Column("tags", sa.Text(), nullable=True),
        sa.Column("metadata", sa.Text(), nullable=True),
        sa.Column("threat_monitoring", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "playbooks",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("conditions", sa.Text(), nullable=False),
        sa.Column("actions", sa.Text(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("updated_at", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "settings",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "threat_events",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("timestamp", sa.Float(), nullable=False),
        sa.Column("node_id", sa.String(length=50), nullable=False),
        sa.Column("source_ip", sa.String(length=50), nullable=False),
        sa.Column("target_ip", sa.String(length=50), nullable=False),
        sa.Column("type", sa.String(length=100), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "threat_intel",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("ip", sa.String(length=100), nullable=False),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column("threat_type", sa.String(length=100), nullable=False),
        sa.Column("severity", sa.String(length=50), nullable=False),
        sa.Column("timestamp", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("threat_intel", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_threat_intel_ip"), ["ip"], unique=False)

    op.create_table(
        "users",
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("password_hash", sa.String(length=128), nullable=False),
        sa.Column("salt", sa.String(length=64), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("created", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("username"),
    )
    op.create_table(
        "vouchers",
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("duration_hours", sa.Integer(), nullable=False),
        sa.Column("data_limit_mb", sa.Integer(), nullable=True),
        sa.Column("is_used", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_table(
        "alerts",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("assignee_id", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("updated_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assignee_id"], ["users.username"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "clients",
        sa.Column("mac", sa.String(length=50), nullable=False),
        sa.Column("ip", sa.String(length=100), nullable=True),
        sa.Column("hostname", sa.String(length=100), nullable=True),
        sa.Column("node_id", sa.String(length=50), nullable=False),
        sa.Column("rssi", sa.Integer(), nullable=True),
        sa.Column("rx_bytes", sa.Integer(), nullable=False),
        sa.Column("tx_bytes", sa.Integer(), nullable=False),
        sa.Column("is_blocked", sa.Boolean(), nullable=False),
        sa.Column("last_seen", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["node_id"], ["nodes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("mac"),
    )
    op.create_table(
        "guest_sessions",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("mac", sa.String(length=50), nullable=False),
        sa.Column("node_id", sa.String(length=50), nullable=False),
        sa.Column("voucher_code", sa.String(length=20), nullable=True),
        sa.Column("authorized_at", sa.Float(), nullable=False),
        sa.Column("expires_at", sa.Float(), nullable=False),
        sa.Column("rx_bytes", sa.Integer(), nullable=False),
        sa.Column("tx_bytes", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["node_id"], ["nodes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "links",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("target", sa.String(length=50), nullable=False),
        sa.Column("auto_discovered", sa.Boolean(), nullable=False),
        sa.Column("metadata", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["source"], ["nodes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target"], ["nodes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "network_configs",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("config_json", sa.Text(), nullable=False),
        sa.Column("node_id", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(["node_id"], ["nodes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "traffic_stats",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("timestamp", sa.Float(), nullable=False),
        sa.Column("node_id", sa.String(length=50), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("rx_bytes", sa.Integer(), nullable=False),
        sa.Column("tx_bytes", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["node_id"], ["nodes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "vault",
        sa.Column("node_id", sa.String(length=50), nullable=False),
        sa.Column("data", sa.Text(), nullable=False),
        sa.Column("encrypted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["node_id"], ["nodes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("node_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("vault")
    op.drop_table("traffic_stats")
    op.drop_table("network_configs")
    op.drop_table("links")
    op.drop_table("guest_sessions")
    op.drop_table("clients")
    op.drop_table("alerts")
    op.drop_table("vouchers")
    op.drop_table("users")
    with op.batch_alter_table("threat_intel", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_threat_intel_ip"))

    op.drop_table("threat_intel")
    op.drop_table("threat_events")
    op.drop_table("settings")
    op.drop_table("playbooks")
    op.drop_table("nodes")
    op.drop_table("integrations")
    op.drop_table("firmwares")
    op.drop_table("beacon_nodes")
    op.drop_table("audit_logs")
    # ### end Alembic commands ###
