"""add_playbooks_table

Revision ID: 0df23b02fff0
Revises: bdbd09e73123
Create Date: 2026-06-16 22:24:21.778258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0df23b02fff0'
down_revision: Union[str, Sequence[str], None] = 'bdbd09e73123'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playbooks', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('conditions',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               nullable=False)
        batch_op.alter_column('actions',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_playbooks_id'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playbooks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_playbooks_id'), ['id'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('actions',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('conditions',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
