"""add_reports_and_pending_executions

Revision ID: f8fcef486962
Revises: 07f3a9bbcb3a
Create Date: 2026-07-08 07:50:45.933830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8fcef486962'
down_revision: Union[str, Sequence[str], None] = '07f3a9bbcb3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('behavior_telemetry',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('avg_dwell_time_ms', sa.Float(), nullable=True),
    sa.Column('avg_flight_time_ms', sa.Float(), nullable=True),
    sa.Column('mouse_velocity_px_s', sa.Float(), nullable=True),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deception_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('honeytoken_id', sa.String(), nullable=True),
    sa.Column('access_time', sa.Float(), nullable=True),
    sa.Column('src_ip', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nat_rules',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('src', sa.String(length=100), nullable=False),
    sa.Column('dst', sa.String(length=100), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nhi_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('service', sa.String(), nullable=True),
    sa.Column('scopes', sa.String(), nullable=True),
    sa.Column('last_used_ip', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('last_used_at', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pending_executions',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('playbook_id', sa.String(length=50), nullable=False),
    sa.Column('alert_id', sa.String(length=50), nullable=False),
    sa.Column('actions', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('timerange_hours', sa.Integer(), nullable=False),
    sa.Column('summary_json', sa.Text(), nullable=False),
    sa.Column('markdown_content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vlan_configs',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('tag', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('subnet', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('playbooks', schema=None) as batch_op:
        batch_op.alter_column('execution_mode',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'autonomous'::character varying"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playbooks', schema=None) as batch_op:
        batch_op.alter_column('execution_mode',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'autonomous'::character varying"))

    op.drop_table('vlan_configs')
    op.drop_table('reports')
    op.drop_table('pending_executions')
    op.drop_table('nhi_tokens')
    op.drop_table('nat_rules')
    op.drop_table('deception_logs')
    op.drop_table('behavior_telemetry')
    # ### end Alembic commands ###
