"""Network configuration command generators (ported + expanded from gns3-config)."""
from __future__ import annotations

import re
import shlex


def _split_csvish(value) -> list[str]:
    if isinstance(value, list):
        raw = value
    else:
        raw = re.split(r"[,\n]+", str(value or ""))
    out = []
    for item in raw:
        item = str(item).strip()
        if item and item not in out:
            out.append(item)
    return out


def _vid(value) -> int | None:
    s = str(value).strip()
    if not s.isdigit():
        return None
    n = int(s)
    return n if 1 <= n <= 4094 else None


def _safe_name(value: str, fallback: str = "config") -> str:
    cleaned = re.sub(r"[^a-zA-Z0-9_\-]", "_", str(value or fallback)).strip("_")
    return cleaned or fallback


def gen_ip(iface: str, addrs: list[str], action: str = "add") -> list[str]:
    cmds = []
    if action == "flush":
        cmds.append(f"ip addr flush dev {iface}")
        for a in addrs:
            cmds.append(f"ip addr add {a} dev {iface}")
        cmds.append(f"ip link set {iface} up")
    elif action == "add":
        for a in addrs:
            cmds.append(f"ip addr add {a} dev {iface}")
        cmds.append(f"ip link set {iface} up")
    elif action == "del":
        for a in addrs:
            cmds.append(f"ip addr del {a} dev {iface}")
    return cmds


def gen_routes(routes: list[dict], action: str = "add") -> list[str]:
    cmds = []
    for r in routes:
        parts = ["ip route", action, r["dst"]]
        if r.get("via"):    parts += ["via",    r["via"]]
        if r.get("dev"):    parts += ["dev",    r["dev"]]
        if r.get("metric"): parts += ["metric", str(r["metric"])]
        cmds.append(" ".join(parts))
    return cmds


def gen_forwarding(ipv4: bool | None = None, ipv6: bool | None = None) -> list[str]:
    cmds = []
    if ipv4 is not None:
        cmds.append(f"sysctl -w net.ipv4.ip_forward={1 if ipv4 else 0}")
    if ipv6 is not None:
        cmds.append(f"sysctl -w net.ipv6.conf.all.forwarding={1 if ipv6 else 0}")
    return cmds


def gen_dhcp(iface: str, action: str = "renew") -> list[str]:
    iface = (iface or "eth0").strip() or "eth0"
    if action == "renew":
        return [
            f"udhcpc -i {iface} 2>/dev/null "
            f"|| dhclient {iface} 2>/dev/null "
            f"|| dhcpcd {iface} 2>/dev/null "
            f"|| echo '(no DHCP client found — install udhcpc, dhclient or dhcpcd)'"
        ]
    if action == "release":
        return [
            f"dhclient -r {iface} 2>/dev/null "
            f"|| udhcpc -R -i {iface} 2>/dev/null "
            f"|| dhcpcd -k {iface} 2>/dev/null "
            f"|| echo '(no DHCP client found)'"
        ]
    return []


def gen_dns(cfg: dict) -> list[str]:
    nameservers = _split_csvish(cfg.get("nameservers"))
    search      = _split_csvish(cfg.get("search"))
    records     = cfg.get("records") or []
    hostname    = str(cfg.get("hostname", "")).strip()
    domain      = str(cfg.get("domain", "")).strip()

    cmds = [
        "# ── DNS / resolver configuration ──────────────────────────",
        "rm -f /tmp/nr_resolv.conf",
        "echo '# Generated by Netrunner' > /tmp/nr_resolv.conf",
    ]
    if search:
        cmds.append(f"echo 'search {' '.join(search)}' >> /tmp/nr_resolv.conf")
    for ns in nameservers:
        cmds.append(f"echo 'nameserver {ns}' >> /tmp/nr_resolv.conf")
    if not nameservers:
        cmds.append("echo '# no nameservers defined yet' >> /tmp/nr_resolv.conf")
    cmds.extend([
        "cp /tmp/nr_resolv.conf /etc/resolv.conf",
        "rm -f /tmp/nr_resolv.conf",
    ])

    if hostname:
        fqdn = f"{hostname}.{domain}" if domain else hostname
        cmds.extend([
            f"echo {shlex.quote(hostname)} > /etc/hostname",
            f"hostname {shlex.quote(hostname)}",
            "sed -i '/# BEGIN NETRUNNER HOSTS/,/# END NETRUNNER HOSTS/d' /etc/hosts 2>/dev/null || true",
            "echo '# BEGIN NETRUNNER HOSTS' >> /etc/hosts",
            f"echo '127.0.1.1 {fqdn} {hostname}' >> /etc/hosts",
        ])
    else:
        cmds.extend([
            "sed -i '/# BEGIN NETRUNNER HOSTS/,/# END NETRUNNER HOSTS/d' /etc/hosts 2>/dev/null || true",
            "echo '# BEGIN NETRUNNER HOSTS' >> /etc/hosts",
        ])

    for record in records:
        name  = str(record.get("name",  "")).strip()
        value = str(record.get("value", "")).strip()
        if name and value:
            cmds.append(f"echo '{value} {name}' >> /etc/hosts")

    cmds.extend([
        "echo '# END NETRUNNER HOSTS' >> /etc/hosts",
        "echo 'DNS configuration updated'",
    ])
    return cmds


def gen_dhcp_server(cfg: dict) -> list[str]:
    iface       = str(cfg.get("interface", "eth1")).strip() or "eth1"
    range_start = str(cfg.get("range_start", "")).strip()
    range_end   = str(cfg.get("range_end", "")).strip()
    mask        = str(cfg.get("mask", "255.255.255.0")).strip() or "255.255.255.0"
    gateway     = str(cfg.get("gateway", "")).strip()
    lease       = str(cfg.get("lease", "12h")).strip() or "12h"
    domain      = str(cfg.get("domain", "")).strip()
    dns_servers = _split_csvish(cfg.get("dns"))
    static_hosts = cfg.get("static_hosts") or []

    cmds = [
        "# ── DHCP server (dnsmasq) ─────────────────────────────────",
        "mkdir -p /etc/dnsmasq.d",
        "rm -f /etc/dnsmasq.d/netrunner-dhcp.conf",
        "echo '# Generated by Netrunner' > /etc/dnsmasq.d/netrunner-dhcp.conf",
        f"echo 'interface={iface}' >> /etc/dnsmasq.d/netrunner-dhcp.conf",
        "echo 'bind-interfaces' >> /etc/dnsmasq.d/netrunner-dhcp.conf",
        "echo 'except-interface=lo' >> /etc/dnsmasq.d/netrunner-dhcp.conf",
        "echo 'dhcp-authoritative' >> /etc/dnsmasq.d/netrunner-dhcp.conf",
    ]
    if range_start and range_end:
        cmds.append(f"echo 'dhcp-range={range_start},{range_end},{mask},{lease}' >> /etc/dnsmasq.d/netrunner-dhcp.conf")
    if gateway:
        cmds.append(f"echo 'dhcp-option=option:router,{gateway}' >> /etc/dnsmasq.d/netrunner-dhcp.conf")
    if dns_servers:
        cmds.append(f"echo 'dhcp-option=option:dns-server,{','.join(dns_servers)}' >> /etc/dnsmasq.d/netrunner-dhcp.conf")
    if domain:
        cmds.extend([
            f"echo 'domain={domain}' >> /etc/dnsmasq.d/netrunner-dhcp.conf",
            f"echo 'local=/{domain}/' >> /etc/dnsmasq.d/netrunner-dhcp.conf",
        ])
    for lease_item in static_hosts:
        mac      = str(lease_item.get("mac",      "")).strip()
        ip       = str(lease_item.get("ip",       "")).strip()
        hostname = str(lease_item.get("hostname", "")).strip()
        if mac and ip:
            host_bits = [mac, ip]
            if hostname:
                host_bits.append(hostname)
            cmds.append(f"echo 'dhcp-host={','.join(host_bits)}' >> /etc/dnsmasq.d/netrunner-dhcp.conf")
    cmds.extend([
        "dnsmasq --test -C /etc/dnsmasq.d/netrunner-dhcp.conf 2>/dev/null || echo '(dnsmasq test failed or missing)'",
        "pkill dnsmasq 2>/dev/null || true",
        "dnsmasq --conf-file=/etc/dnsmasq.d/netrunner-dhcp.conf 2>/tmp/nr-dnsmasq.log || cat /tmp/nr-dnsmasq.log",
    ])
    return cmds


def gen_nat(cfg: dict) -> list[str]:
    outbound   = str(cfg.get("outbound_iface", "eth0")).strip() or "eth0"
    inbound    = str(cfg.get("inbound_iface",  "eth1")).strip() or "eth1"
    source     = str(cfg.get("source_subnet",  "")).strip()
    masquerade = bool(cfg.get("masquerade", True))
    forwards   = cfg.get("port_forwards") or []

    cmds = [
        "# ── NAT / port forwarding via iptables ─────────────────────",
        "sysctl -w net.ipv4.ip_forward=1",
        "iptables -N NR_FORWARD 2>/dev/null || true",
        "iptables -F NR_FORWARD",
        "iptables -D FORWARD -j NR_FORWARD 2>/dev/null || true",
        "iptables -A FORWARD -j NR_FORWARD",
        "iptables -t nat -N NR_NAT 2>/dev/null || true",
        "iptables -t nat -F NR_NAT",
        "iptables -t nat -D PREROUTING -j NR_NAT 2>/dev/null || true",
        "iptables -t nat -D POSTROUTING -j NR_NAT 2>/dev/null || true",
        "iptables -t nat -A PREROUTING -j NR_NAT",
        "iptables -t nat -A POSTROUTING -j NR_NAT",
        "iptables -A NR_FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT",
    ]
    if source:
        cmds.append(f"iptables -A NR_FORWARD -i {inbound} -o {outbound} -s {source} -j ACCEPT")
    if masquerade:
        parts = ["iptables", "-t", "nat", "-A", "NR_NAT"]
        if source:
            parts += ["-s", source]
        parts += ["-o", outbound, "-j", "MASQUERADE"]
        cmds.append(" ".join(parts))
    for rule in forwards:
        proto       = str(rule.get("proto", "tcp")).strip() or "tcp"
        ext_port    = str(rule.get("external_port",  "")).strip()
        target_ip   = str(rule.get("target_ip",      "")).strip()
        target_port = str(rule.get("target_port",    "")).strip() or ext_port
        if not (ext_port and target_ip):
            continue
        cmds.append(
            f"iptables -t nat -A NR_NAT -i {outbound} -p {proto} --dport {ext_port} "
            f"-j DNAT --to-destination {target_ip}:{target_port}"
        )
        cmds.append(
            f"iptables -A NR_FORWARD -i {outbound} -o {inbound} -p {proto} -d {target_ip} "
            f"--dport {target_port} -j ACCEPT"
        )
    cmds.extend([
        "iptables -S NR_FORWARD 2>/dev/null || true",
        "iptables -t nat -S NR_NAT 2>/dev/null || true",
    ])
    return cmds


def gen_reset_node() -> list[str]:
    return [
        "# ── Reset network configuration ─────────────────────────────",
        "sh -lc 'for dev in $(ip -o link show | awk -F\": \" \"{print \\$2}\" | cut -d@ -f1 | grep -v \"^lo$\"); do ip addr flush dev \"$dev\" 2>/dev/null || true; ip link set \"$dev\" down 2>/dev/null || true; ip link set \"$dev\" up 2>/dev/null || true; done'",
        "ip route flush table main 2>/dev/null || true",
        "ip -6 route flush table main 2>/dev/null || true",
        "sh -lc 'for dev in $(ip -o link show type wireguard 2>/dev/null | awk -F\": \" \"{print \\$2}\" | cut -d@ -f1); do wg-quick down \"$dev\" 2>/dev/null || ip link del \"$dev\" 2>/dev/null || true; done'",
        "sh -lc 'for dev in $(ip -o link show type vlan 2>/dev/null | awk -F\": \" \"{print \\$2}\" | cut -d@ -f1); do ip link del \"$dev\" 2>/dev/null || true; done'",
        "sh -lc 'for dev in $(ip -o link show type bridge 2>/dev/null | awk -F\": \" \"{print \\$2}\" | cut -d@ -f1); do [ \"$dev\" = \"docker0\" ] && continue; ip link set \"$dev\" down 2>/dev/null || true; ip link del \"$dev\" type bridge 2>/dev/null || true; done'",
        "sysctl -w net.ipv4.ip_forward=0 2>/dev/null || true",
        "sysctl -w net.ipv6.conf.all.forwarding=0 2>/dev/null || true",
        "nft flush ruleset 2>/dev/null || true",
        "iptables -F 2>/dev/null || true",
        "iptables -t nat -F 2>/dev/null || true",
        "iptables -t mangle -F 2>/dev/null || true",
        "iptables -X NR_FORWARD 2>/dev/null || true",
        "iptables -t nat -X NR_NAT 2>/dev/null || true",
        "iptables -P INPUT ACCEPT 2>/dev/null || true",
        "iptables -P FORWARD ACCEPT 2>/dev/null || true",
        "iptables -P OUTPUT ACCEPT 2>/dev/null || true",
        "ufw --force disable 2>/dev/null || true",
        "ufw --force reset 2>/dev/null || true",
        "pkill dnsmasq 2>/dev/null || true",
        "rm -f /etc/dnsmasq.d/netrunner-dhcp.conf /tmp/nr-dnsmasq.log 2>/dev/null || true",
        "printf '# resolver reset by Netrunner\\n' > /etc/resolv.conf",
        "sed -i '/# BEGIN NETRUNNER HOSTS/,/# END NETRUNNER HOSTS/d' /etc/hosts 2>/dev/null || true",
        "rm -f /etc/wireguard/*.conf 2>/dev/null || true",
        "echo 'Network configuration reset complete'",
    ]


def gen_vlan_router(iface: str, vlans: list[dict]) -> list[str]:
    iface = (iface or "eth0").strip() or "eth0"
    cmds = [
        f"# ── Router-on-a-stick on {iface} ───────────────────────────",
        "modprobe 8021q 2>/dev/null || true",
        f"ip link set {iface} up",
    ]
    seen = set()
    for v in vlans or []:
        vid = _vid(v.get("id"))
        if not vid or vid in seen:
            continue
        seen.add(vid)
        sub = f"{iface}.{vid}"
        if v.get("description"):
            cmds.append(f"# VLAN {vid}: {v['description']}")
        cmds.append(f"ip link add link {iface} name {sub} type vlan id {vid}")
        cmds.append(f"ip link set {sub} up")
        addr = (v.get("address") or "").strip()
        if addr:
            cmds.append(f"ip addr add {addr} dev {sub}")
    return cmds


def gen_vlan_switch(bridge: str, vlans: list[dict], ports: list[dict]) -> list[str]:
    bridge = (bridge or "br0").strip() or "br0"
    cmds = [
        f"# ── VLAN-aware switch on {bridge} ───────────────────────────",
        f"ip link add name {bridge} type bridge vlan_filtering 1 2>/dev/null || "
        f"ip link set {bridge} type bridge vlan_filtering 1",
        f"ip link set {bridge} up",
        f"bridge vlan del dev {bridge} vid 1 self 2>/dev/null || true",
    ]
    for v in vlans or []:
        vid = _vid(v.get("id"))
        if not vid:
            continue
        name = (v.get("name") or "").strip()
        cmds.append(f"# VLAN {vid}" + (f" ({name})" if name else ""))

    for p in ports or []:
        iface = (p.get("iface") or "").strip()
        if not iface:
            continue
        mode = p.get("mode", "access")
        cmds.append("")
        cmds.append(f"# Port {iface} — {mode}")
        cmds.append(f"ip link set {iface} master {bridge}")
        cmds.append(f"ip link set {iface} up")
        cmds.append(f"bridge vlan del dev {iface} vid 1 2>/dev/null || true")
        if mode == "access":
            vid = _vid(p.get("vlan"))
            if vid:
                cmds.append(f"bridge vlan add dev {iface} vid {vid} pvid untagged")
        else:
            allowed = []
            raw_allowed = p.get("allowed", [])
            if isinstance(raw_allowed, str):
                raw_allowed = [x for x in re.split(r"[,\s]+", raw_allowed) if x]
            for x in raw_allowed:
                vid = _vid(x)
                if vid and vid not in allowed:
                    allowed.append(vid)
            for vid in allowed:
                cmds.append(f"bridge vlan add dev {iface} vid {vid} tagged")
            pvid = _vid(p.get("pvid"))
            if pvid:
                cmds.append(f"bridge vlan add dev {iface} vid {pvid} pvid untagged")
    return cmds


def gen_wireguard(iface: str, cfg: dict) -> list[str]:
    lines = ["[Interface]"]
    for k, lbl in [
        ("private_key", "PrivateKey"), ("address", "Address"),
        ("listen_port", "ListenPort"), ("dns", "DNS"),
        ("mtu", "MTU"), ("post_up", "PostUp"), ("post_down", "PostDown"),
    ]:
        if cfg.get(k):
            lines.append(f"{lbl} = {cfg[k]}")
    for peer in cfg.get("peers", []):
        lines += ["", "[Peer]"]
        for k, lbl in [
            ("public_key", "PublicKey"), ("preshared_key", "PresharedKey"),
            ("endpoint", "Endpoint"), ("allowed_ips", "AllowedIPs"),
            ("persistent_keepalive", "PersistentKeepalive"),
        ]:
            if peer.get(k):
                lines.append(f"{lbl} = {peer[k]}")
    conf = "\n".join(lines)

    return [
        "# ── Install WireGuard ───────────────────────────────────────",
        "apk add wireguard-tools 2>/dev/null || apt-get install -y wireguard-tools 2>/dev/null || yum install -y wireguard-tools 2>/dev/null || true",
        "",
        "# ── Keypair generation (run manually on device) ─────────────",
        "# wg genkey | tee /etc/wireguard/privatekey | wg pubkey > /etc/wireguard/publickey",
        "# cat /etc/wireguard/privatekey && cat /etc/wireguard/publickey",
        "",
        f"# ── Write /etc/wireguard/{iface}.conf ──────────────────────",
        "mkdir -p /etc/wireguard",
        f"cat > /etc/wireguard/{iface}.conf << 'EOF'",
        *conf.split("\n"),
        "EOF",
        f"chmod 600 /etc/wireguard/{iface}.conf",
        "",
        "# ── Activate ────────────────────────────────────────────────",
        f"wg-quick up {iface}",
        "",
        "# ── Persist across reboots ──────────────────────────────────",
        f"rc-update add wg-quick.{iface} default 2>/dev/null || "
        f"systemctl enable wg-quick@{iface} 2>/dev/null || true",
    ]


def gen_persist_script(name: str, commands: list[str]) -> list[str]:
    script_name = _safe_name(name, "config")
    marker = "__NETRUNNER_EOF__"
    script_path = f"/etc/local.d/{script_name}.start"
    body = ["#!/bin/sh", "# Generated by Netrunner", ""]
    body.extend(commands or [])

    return [
        "# ── Install persistent boot script ──────────────────────────",
        "mkdir -p /etc/local.d",
        f"cat > {script_path} << '{marker}'",
        *body,
        marker,
        f"chmod +x {script_path}",
        "rc-update add local default 2>/dev/null || true",
        f"echo 'Persistent config installed: {script_path}'",
    ]


def gen_backup_commands(paths: dict) -> list[str]:
    def q(s): return shlex.quote(s)
    return [
        "# ── Backup current network state ────────────────────────────",
        f"rm -rf {q(paths['dir'])}",
        f"mkdir -p {q(paths['wireguard'])}",
        f"sh -lc {q(f'ip address save > {paths[\"ip_addr\"]} 2>/dev/null || :')}",
        f"sh -lc {q(f'ip route save > {paths[\"ip_route\"]} 2>/dev/null || :')}",
        f"sh -lc {q(f'ip -6 route save > {paths[\"ip6_route\"]} 2>/dev/null || :')}",
        f"sh -lc {q(f'sysctl -n net.ipv4.ip_forward > {paths[\"ipv4_forward\"]} 2>/dev/null || echo 0 > {paths[\"ipv4_forward\"]}')}",
        f"sh -lc {q(f'sysctl -n net.ipv6.conf.all.forwarding > {paths[\"ipv6_forward\"]} 2>/dev/null || echo 0 > {paths[\"ipv6_forward\"]}')}",
        f"sh -lc {q(f'iptables-save > {paths[\"iptables\"]} 2>/dev/null || :')}",
        f"sh -lc {q(f'nft list ruleset > {paths[\"nft\"]} 2>/dev/null || :')}",
        f"cp /etc/resolv.conf {q(paths['resolv'])} 2>/dev/null || true",
        f"cp /etc/hosts {q(paths['hosts'])} 2>/dev/null || true",
        f"cp /etc/dnsmasq.d/netrunner-dhcp.conf {q(paths['dnsmasq'])} 2>/dev/null || true",
        f"cp -r /etc/wireguard/. {q(paths['wireguard'])}/ 2>/dev/null || true",
        f"echo 'Backup created: {paths['dir']}'",
    ]
